name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      falkordb:
        image: falkordb/falkordb:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      FALKORDB: falkordb:6379
    container:
      image: perldocker/perl-tester:5.42     # https://hub.docker.com/r/perldocker/perl-tester
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Perl dependencies
        run: |
          cpanm --notest --installdeps .

      - name: Wait for the FalkorDB service to become available
        run: |
          for i in $(seq 1 30); do
            if bash -c "echo > /dev/tcp/falkordb/6379" 2>/dev/null; then
              break
            fi
            sleep 1
          done

      - name: Run tests
        run: |
          perl Makefile.PL
          make
          make test
          make manifest
          make dist

      - name: Run tests with prove
        run: |
          prove -Ilib -lv t/

